version: "3"

services:
  proxy:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  main:
    build:
      context: .
    volumes:
      - ./main:/var/www/main
    environment:
      VIRTUAL_HOST: placehold.local.entwickl.de
      APP_NAME: placehold
      APP_TEXT_LEAD: Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt