services:
  amber:
    build:
      context: .
    ports:
      - 127.0.0.1:8080:80
    volumes:
      - ./app:/app
    environment:
      APP_NAME: amber
      APP_TEXT_LEAD: Simple Docker Placeholder Website
