services:
  amber:
    image: amber:local
    build:
      context: .
    ports:
      - 127.0.0.1:8080:80
    volumes:
      - ./app:/app
    environment:
      APP_NAME: amber
      APP_TEXT_LEAD: Simple Docker Placeholder Website

  amber-markdown:
    image: amber:local
    build:
      context: .
    ports:
      - 127.0.0.1:8081:80
    volumes:
      - ./demo/index.md:/app/content/index.md:ro
      - ./demo/logo.svg:/app/content/logo.svg:ro
    environment:
      APP_NAME: amber
