version: "3"

services:
  proxy:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  main:
    build:
      context: .
    volumes:
      - ./main:/app
    environment:
      VIRTUAL_HOST: amber.127.0.0.1.xip.io
      APP_NAME: amber
      APP_TEXT_LEAD: Simple Docker Placeholder Website